### PR TITLE
Use big.Int for balances #12

### PR DESCRIPTION
**Pull request by e-asphyx**

### CODE REVIEW

**Comment by juliusv** [comment]
Ah, yeah, I had left this at `string` at first to be safe because I understood too little about Go's bignum types and Tezos' decimal places. Can it really only be integers though? https://tezos.gitlab.io/betanet/api/rpc.html#get-block-id-context-contracts-contract-id-balance says it's a "Decimal representation of a big number", so it could have an arbitary number of digits after the decimal point?

**Comment by e-asphyx** [comment]
According to comment to binary encoding balances are integer.

**Comment by juliusv** [comment]
Ah ok, I googled what a "Zarith number" is and it seems to be only (arbitrary precision) integers, so I assume that's what you mean. Ok!

**Comment by juliusv** [comment]
👍

**Pull request merged**
